version: '3'

services:
  mysql:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: security_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  your_service_name:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    environment:
      SERVER_PORT: 1111
      SPOONACULAR_BASE_URL: https://api.spoonacular.com/mealplanner/generate
      SPOONACULAR_API_KEY: cf71138d62d74cd9877ee1e30e14582b
      LOGGING_LEVEL_org_springframework_web_client_RestTemplate: DEBUG
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: practice
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dietify?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      HOST_ADDRESS: localhost
      SMTP_EMAIL: rashadchowki42@gmail.com
      SMTP_KEY: fovo berp krln xgji
    depends_on:
      - mysql
      - mongodb
    restart: always

volumes:
  mysql_data:
  mongodb_data:
