version: '3'

services:
  mysql:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dietify
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  your_service_name:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dietify?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MONGODB_URI: mongodb://mongodb:27017/dietify
      SERVER_ADDRESS: 0.0.0.0
    depends_on:
      - mysql
      - mongodb
    restart: always

volumes:
  mysql_data:
  mongodb_data:
